### ISSUE TITLE
部署后失败

### ISSUE THREAD

**Issue by nlxxtw** [ourongxing/newsnow#1]
是要自己弄api嘛
![image](https://github.com/user-attachments/assets/293f9a9a-786b-47ee-a5e7-e287cf946a25)

**Comment by nlxxtw** [comment]
部署在vercel上了

**Comment by ourongxing** [comment]
不支持 vercel，目前只能部署到 cloudflare page，或者服务器

**Comment by charley008** [comment]
不弄个docker版吗？

**Comment by ourongxing** [comment]
@charley008 @nlxxtw 文档写好了，支持部署到 Docker 以及 Vercel。
