### ISSUE TITLE
部署成功但是接口报错，提示找不到数据库

### ISSUE THREAD

**Issue by judahxu** [ourongxing/newsnow#17]
如果不需要登录，缓存，可以直接部署到 Cloudflare Pages，Vercel 等。Fork 之后在对应平台上导入即可。

Cloudflare Pages 需要填入构建命令 pnpm run build, 构建输出文件夹 dist/output/public。

没有操作 D1 sql  没有配置环境变量

按照文档操作，cloudflare部署成功后但是访问的时候发现接口一直报找不到数据库。

**Comment by ourongxing** [comment]
不清楚，我测试过，这个报错不会影响运行啊，你在 cloudflare 删除项目，重新导入。

**Comment by judahxu** [comment]
![image](https://github.com/user-attachments/assets/49defe75-1cca-42c0-8091-b7341046daf4)
![image](https://github.com/user-attachments/assets/4e878395-04d7-4a1c-a990-1fc958d2e4fa)
是不是和这个D1数据库必须要配置

**Comment by judahxu** [comment]
![image](https://github.com/user-attachments/assets/567a7371-9d6c-4ac8-b707-d8ad37488a19)
这个报错

**Comment by judahxu** [comment]
![image](https://github.com/user-attachments/assets/bced306f-f874-4136-a0b9-2dd9a6e2cb46)

**Comment by ourongxing** [comment]
倒也不是这个问题，现在修好了。
