### ISSUE TITLE
oauth登录，急缺小红书热搜

### ISSUE THREAD

**Issue by weiyi88** [ourongxing/newsnow#19]
1，github oauth 登录，有问题，我按照要求写了，G_CLIENT_ID，G_CLIENT_SECRET 
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/9ffcc15f-db5a-48eb-8406-6800aca47bc6">

点击没反应，出了这个数据包

2，作者大大，急需小红书热榜，能增加个么

**Comment by ourongxing** [comment]
忘写了 callback url 的路径是 `api/oauth/github`

**Comment by weiyi88** [comment]
作者大大，我能二开么，这太棒了，很多朋友都用来当书签页

**Comment by ourongxing** [comment]
MIT 开源，随意使用，作为书签页确实也是个好主意。
