### ISSUE TITLE
v2ex 403了

### ISSUE THREAD

**Issue by weiyi88** [ourongxing/newsnow#20]
<img width="862" alt="image" src="https://github.com/user-attachments/assets/630e7eb0-9952-4c7b-982a-27c43e63fcb8">

{
    "url": "/api/s/v2ex-share",
    "statusCode": 500,
    "statusMessage": "",
    "message": "[GET] \"https://www.v2ex.com/feed/ideas.json\": 403 Forbidden"
}

**Comment by ar0c** [comment]
@ourongxing 请问为什么我最新版本还是有相同的问题？
