### ISSUE TITLE
Hacker News 和 Product Hunt 获取失败，代理失效吗？

### ISSUE THREAD

**Issue by z1s8h5** [ourongxing/newsnow#22]
![image](https://github.com/user-attachments/assets/ea8ef028-3269-43c6-8cd7-3a192c5b7c2f)

1. 代理失效吗，如何更新代理设置？
2. 如何添加新的热搜（比如360热搜）？

**Comment by ourongxing** [comment]
1. 代理自行设置
https://github.com/ourongxing/newsnow/blob/55709e1420183433dae5479ab7a54fd5c1ac38da/server/utils/fetch.ts#L1-L9

```
import { ProxyAgent } from "undici";
import { $fetch } from "ofetch";

const proxyAgent = new ProxyAgent("http://localhost:3128");
const data = await $fetch("https://icanhazip.com", { dispatcher: proxyAgent });
```

2. 新的 source 看源码添加。
`shared/sources.ts` `server/sources` 照着做就行了。

**Comment by JarboU** [comment]
请问一下，docker部署的 [newsnow/server/utils/fetch.ts]这个文件路径在哪里？

**Comment by ljbkevin** [comment]
> 从源码开始构建

用docker-compose.yml搭建的是不是加不了代理了。。请问大佬如何加代理

**Comment by ourongxing** [comment]
> > 从源码开始构建
> 
> 用docker-compose.yml搭建的是不是加不了代理了。。请问大佬如何加代理

直接改源码，我不会内置的。这个项目主要部署在 cloudflare 上。

**Comment by baiwfg2** [comment]
> > > 从源码开始构建
> > 
> > 
> > 用docker-compose.yml搭建的是不是加不了代理了。。请问大佬如何加代理
> 
> 直接改源码，我不会内置的。这个项目主要部署在 cloudflare 上。

具体的代理路径当然不内置，但按理说应该是能在yml 中配好http_proxy变量来改变代码发起请求走代理的，但是无论是使用`http://172.17.0.1:10809`还是 `http://host.docker.internal:10809`（我的代理在宿主机），始终没走通。。
