### ISSUE TITLE
开发模式部署，数据库会用到吗？

### ISSUE THREAD

**Issue by smalldeer1982** [ourongxing/newsnow#24]
pnpm i
pnpm dev

使用开发模式部署，是否会用到本地数据库，推送过来的数据放在哪里呢，想数据落地在本地数据库是否可行

**Comment by ourongxing** [comment]
.data 文件夹。之前默认是 dev 下不使用缓存。最新的代码默认开启了。

开发模式下由于没打包，性能比较低。
