### ISSUE TITLE
github登录提示500 Request Error

### ISSUE THREAD

**Issue by xhily** [ourongxing/newsnow#31]
500 Request Error
internal server error

**Comment by 0x5c0f** [comment]
是部署到vercel的么，  这个问题我看了下这边的日志，说是没有配置数据库的原因  `Error: Database connection "default" not configured. at (index.mjs:1:151215) at (index.mjs:1:218623) at (index.mjs:1:72012) at (index.mjs:1:72492) at (index.mjs:1:75701) at (index.mjs:1:148949)`

**Comment by xhily** [comment]
部署到cloudflare 上  数据库应该是绑定了吧
![image](https://github.com/user-attachments/assets/9e8c3d42-8e19-4171-9e17-2f65dd0bae2a)

**Comment by 0x5c0f** [comment]
可以看下日志，应该问题是一样的

**Comment by xhily** [comment]
是我的问题，已经好了

**Comment by Ssiswent** [comment]
我也遇到了，是docker部署的，用的portainer

**Comment by Ssiswent** [comment]
![Image](https://github.com/user-attachments/assets/ef647492-f905-456e-9a32-1c5f59d60b20)
