### ISSUE TITLE
Hacker News 和 Product Hunt 一直出不来内容，走网关代理也是。是否可提供屏蔽配置，加载不出来的页面上就不显示了。

### ISSUE THREAD

**Issue by fc6a1b03** [ourongxing/newsnow#33]
v0.0.9 至 v0.0.16 一直这样，应用部署在k3s集群的。
![图片](https://github.com/user-attachments/assets/1e708eae-8888-451d-be43-b4a76f7c7b66)

**Comment by ourongxing** [comment]
禁用
https://github.com/ourongxing/newsnow/blob/02f6f008fa954380f67cbd89d84fde498224eeba/shared/sources.ts#L80-L92C5

代理
[#22 ](https://github.com/ourongxing/newsnow/issues/22#issuecomment-2446466817)

**Comment by fc6a1b03** [comment]
> 禁用 https://github.com/ourongxing/newsnow/blob/02f6f008fa954380f67cbd89d84fde498224eeba/shared/sources.ts#L80-L92C5
> 
> 代理 [#22 ](https://github.com/ourongxing/newsnow/issues/22#issuecomment-2446466817)

https://github.com/fc6a1b03/newsnow/blob/main/server/utils/fetch.ts
代理部分可以加进去吗？已经验证过了，主要是还得维护一个版本和同步`ourongxing/newsnow`的太麻烦了。

**Comment by ourongxing** [comment]
需要看看怎么能兼容 cloudflare worker 环境

**Comment by ourongxing** [comment]
没多大必要 ，因为只有两个内容源需要代理，而国内的源如果全局代理了速度反而会慢，所以还是根据自己的环境来修改代码比较好，或者你维护一个方便 docker 国内使用的版本也行。

**Comment by kahakaha** [comment]
我在想，是不是可以通过将fetch再封装一层，达到在程序内分流的效果，这样可以避免原作者提到全局代理的问题（虽然我觉得全局没什么问题）

```javascript
// server/utils/fetch.ts

// 保留原作者的没有代理的 fetcher 和 @fc6a1b03 的有代理的fetch，这里省略了除代理外的其他部分
const fetchWithNoProxy = $fetch.create(...);
const fetchWithProxy = $fetch.create(...,{ dispatcher: proxyAgent });

// 从环境变量或者某个地方读取需要代理哪些网站
const needProxy = ["site1", "site2"];

export const myFetch = (url: string, ...args: any[]) => {
    const hostname = getHostname(url)
    
    // 根据域名选择是否使用代理
    if (needProxy.includes(hostname)) {
        fetchWithProxy(url, ...args);
    } else {
        fetchWithNoProxy(url, ...args);
    }
}
```

ps: 代码写得比较随意，仅供示意
