### ISSUE TITLE
pnpm install 失败

### ISSUE THREAD

**Issue by weiyi88** [ourongxing/newsnow#40]
我 pnpm install 时候报错这个问题

bilibili-video-downloader(base) ➜  newsnow git:(feature/rongye/add_36_huxiu) pnpm install 
 WARN  Ignoring broken lockfile at /Users/bluefocus_work/Desktop/newsnow: Lockfile /Users/bluefocus_work/Desktop/newsnow/pnpm-lock.yaml not compatible with current pnpm
 ERR_PNPM_PATCH_NOT_APPLIED  The following patches were not applied: dayjs

Either remove them from "patchedDependencies" or update them to match packages in your dependencies.
Progress: resolved 1315, reused 1172, downloaded 0, added 0

然后package.jsno 有这个内容
 "pnpm": {
    "patchedDependencies": {
      "dayjs": "patches/dayjs.patch"
    }
  },
  
  我应该怎么解决这个问题。我问了chat 需要我手动安装该补丁，按照推荐操作也失败了
但是我删除了这行内容，pnpm install 就没问题，这个补丁重要么

**Comment by ourongxing** [comment]
dayjs 的版本不对，不过对当前功能没什么影响。
